version: '2'

# Define the services/containers to be run
services:

  openserver:  #name of your service

    build: .
    #command: nodemon app/route.js
    command: >
      sh -c "/wait &&
             node app/setup.js && 
             nodemon app/route.js --ignore data/"

    ports:
      - "8000:8000" #specify ports forwarding

    links:
      - database # link this service to the database service

    depends_on:
      - database

    volumes:
      - ./data:/usr/src/minnoserver/data
      - ./config.docker.js:/usr/src/minnoserver/config.js
      - ./app:/usr/src/minnoserver/app

    environment:
      WAIT_HOSTS: database:27017

      PORT: 8000
      MINNO_BASE_FOLDER: '/usr/src/minnoserver'
      MINNO_MONGO_URL: 'mongodb://database:27017/minnodb'
      MINNO_SERVER_URL: 'http://localhost:8000'
      MINNO_DASHBOARD_URL: '//cdn.jsdelivr.net/gh/ProjectImplicit/researchDashboard@1'
      MINNO_PLAYER_URL : '//cdn.jsdelivr.net/gh/minnojs/minno-quest@0.2/dist/'

  database: # name of the service

    image: mongo # specify image to build container from
    restart: always
    volumes:
      - ./data/db:/data/db
